sonar.projectKey=23suca03-dineshkarthick_resort-crm-frontend
sonar.organization=23suca03-dineshkarthick

# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=resort-crm-frontend
#sonar.projectVersion=1.0

sonar.sources=src
sonar.exclusions=src/__tests__/**,src/main.jsx
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
